/*
--------------------------------------------------
cvtest2.c

This is the simple nachos user program to test 
if wait, signal and broadcast sys calls work on 
invalid reference and on the reference that is
not yet created or by just passing one reference

--------------------------------------------------
*/
#include "syscall.h"


int main()
{
	int cv4;
	int cv5=2;
	int lock2=7;
	int lock1=CreateLock();
	Write("\n Running cvtest2.c\n",22,1);
	cv4=CreateCondition();

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON A CV WITHOUT PASSING ANY ARGUEMENT",74,1);
	WaitCondition(); /* TRYING TO WAIT ON A CV WITHOUT PASSING ANY ARGUEMENT */
	SignalCondition();	/* TRYING TO SINGAL ON A CV WITHOUT PASSING ANY ARGUEMENT */
	BroadcastCondition(); /* TRYING TO BROADCAST ON A CV WITHOUT PASSING ANY ARGUEMENT */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON A CV BY PASSING JUST THE CV ARGUEMENT",77,1);
	WaitCondition(cv5); /* TRYING TO WAIT ON A CV BY PASSING JUST A SINGLE ARGUEMENT */
	SignalCondition(cv5);	/* TRYING TO SINGAL ON A BY PASSING JUST A SINGLE ARGUEMENT */
	BroadcastCondition(cv5); /* TRYING TO BROADCAST ON A CV BY PASSING JUST A SINGLE ARGUEMENT */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON A CV BY PASSING JUST THE LOCK ARGUEMENT",79,1);
	WaitCondition(lock1); /* TRYING TO WAIT ON A CV WITHOUT PASSING ANY ARGUEMENT */
	SignalCondition(lock1);	/* TRYING TO SINGAL ON A CV WITHOUT PASSING ANY ARGUEMENT */
	BroadcastCondition(lock1); /* TRYING TO BROADCAST ON A CV WITHOUT PASSING ANY ARGUEMENT */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON  A CV THAT IS NOT YET CREATED",69,1);
	WaitCondition(cv5,lock1); /* TRYING TO WAIT ON  A CV THAT IS NOT YET CREATED */
	SignalCondition(cv5,lock1);	/* TRYING TO SINGAL ON A CV THAT IS NOT YET CREATED */
	BroadcastCondition(cv5,lock1); /* TRYING TO BROADCAST ON A CV THAT IS NOT YET CREATED */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON  A CV WITH A LOCK THAT  IS NOT YET CREATED",82,1);
	WaitCondition(cv4,lock2); /* TRYING TO WAIT ON  A CV WITH A LOCK THAT  IS NOT YET CREATED */
	SignalCondition(cv4,lock2);	/* TRYING TO SINGAL ON A CV WITH A LOCK THAT  IS NOT YET CREATED */
	BroadcastCondition(cv4,lock2); /* TRYING TO BROADCAST ON A CV WITH A LOCK THAT  IS NOT YET CREATED */


	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON  A CV PASSING A INVALID CV REFERENCE -1",79,1);
	WaitCondition(-1,lock1); /* TRYING TO WAIT ON  A CV PASSING A INVALID REFERENCE */
	SignalCondition(-1,lock1); /* TRYING TO SINGAL ON A CV PASSING A INVALID REFERENCE */
	BroadcastCondition(-1,lock1); /* TRYING TO BROADCAST ON A CV PASSING A INVALID REFERENCE */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON  A CV PASSING A INVALID CV REFERENCE 70000",82,1);
	WaitCondition(70000,lock1); /* TRYING TO WAIT ON  A CV PASSING A INVALID REFERENCE */
	SignalCondition(70000,lock1); /* TRYING TO SINGAL ON A CV PASSING A INVALID REFERENCE */
	BroadcastCondition(70000,lock1); /* TRYING TO BROADCAST ON A CV PASSING A INVALID REFERENCE */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON  A CV PASSING A INVALID LOCK REFERENCE -1",81,1);
	WaitCondition(cv4,-1); /* TRYING TO WAIT ON  A CV WITH A LOCK THAT  IS NOT YET CREATED */
	SignalCondition(cv4,-1);	/* TRYING TO SINGAL ON A CV WITH A LOCK THAT  IS NOT YET CREATED */
	BroadcastCondition(cv4,-1); /* TRYING TO BROADCAST ON A CV WITH A LOCK THAT  IS NOT YET CREATED */

	Write("\nTRYING TO WAIT SIGNAL AND BROADCAST ON  A CV PASSING A INVALID LOCK REFERENCE 70000",84,1);
	WaitCondition(cv4,70000); /* TRYING TO WAIT ON  A CV WITH A LOCK THAT  IS NOT YET CREATED */
	SignalCondition(cv4,70000);	/* TRYING TO SINGAL ON A CV WITH A LOCK THAT  IS NOT YET CREATED */
	BroadcastCondition(cv4,70000); /* TRYING TO BROADCAST ON A CV WITH A LOCK THAT  IS NOT YET CREATED */

	Exit(0);
}